In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics._plot.confusion_matrix import ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv('/content/Currentdata.csv')
#print(data)
df = pd.DataFrame(data)

In [5]:
df

RecordNo          DateTime  RPhaseCurrentAmp  YPhaseCurrentAmp  \
0             1  01-08-2022 07:59              0.14              0.06   
1             2  01-08-2022 08:00              0.15              0.05   
2             3  01-08-2022 08:02              0.11              0.05   
3             4  01-08-2022 08:03              0.11              0.05   
4             5  01-08-2022 08:04              0.43              0.25   
...         ...               ...               ...               ...   
42193     42194  08-09-2022 23:55              0.47              0.07   
42194     42195  08-09-2022 23:56              0.44              0.10   
42195     42196  08-09-2022 23:57              0.44              0.10   
42196     42197  08-09-2022 23:58              0.43              0.09   
42197     42198  08-09-2022 23:59              0.43              0.09   

       BPhaseCurrentAmp  TotalCurrentAmp  MBRGeyser1  BRGeyser2  
0                  0.05             0.25           0          0  
1                  0.05             0.24           0          0  
2                  0.05             0.22           0          0  
3                  0.05             0.22           0          0  
4                  0.04             0.71           0          0  
...                 ...              ...         ...        ...  
42193              0.05             0.59           0          0  
42194              0.04             0.59           0          0  
42195              0.05             0.58           0          0  
42196              0.04             0.57           0          0  
42197              0.05             0.57           0          0  

[42198 rows x 8 columns]

In [4]:
print(data.dtypes)

RecordNo              int64
DateTime             object
RPhaseCurrentAmp    float64
YPhaseCurrentAmp    float64
BPhaseCurrentAmp    float64
TotalCurrentAmp     float64
MBRGeyser1            int64
BRGeyser2             int64
dtype: object


In [6]:
feature_cols = ['TotalCurrentAmp', 'RPhaseCurrentAmp', 'YPhaseCurrentAmp', 'BPhaseCurrentAmp']
X= data[feature_cols]
y= data['MBRGeyser1']
y1 = data['BRGeyser2']

In [9]:
#for Geyser 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
#for Geyser 2
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.2, random_state=1)

In [10]:
knn = KNeighborsClassifier(11)

rfc = RandomForestClassifier(n_estimators = 7,criterion = 'entropy',random_state =7)
gnb = GaussianNB()
svc = SVC()
MLP =  MLPClassifier(activation = 'logistic' ,solver='adam', alpha=0.0001, hidden_layer_sizes=(100,), max_iter =200)
lc = LogisticRegression()

In [11]:
for clf in (rfc, knn, svc, lc, MLP, gnb):
    clf.fit(X_train, y_train)
    Y_pred = clf.predict(X_test)
    print("Accuracy score of ",
          clf.__class__.__name__,
          "=", 100 * accuracy_score(y_test, Y_pred))
    print(confusion_matrix(y_test, Y_pred))

Accuracy score of  RandomForestClassifier = 99.97630331753554
[[8240    2]
 [   0  198]]
Accuracy score of  KNeighborsClassifier = 99.97630331753554
[[8240    2]
 [   0  198]]
Accuracy score of  SVC = 99.95260663507109
[[8238    4]
 [   0  198]]
Accuracy score of  LogisticRegression = 99.95260663507109
[[8239    3]
 [   1  197]]
Accuracy score of  MLPClassifier = 99.95260663507109
[[8238    4]
 [   0  198]]
Accuracy score of  GaussianNB = 99.70379146919431
[[8217   25]
 [   0  198]]


In [12]:
for clf1 in (rfc, knn, svc, lc, MLP, gnb):
    clf1.fit(X1_train, y1_train)
    Y1_pred = clf1.predict(X1_test)
    print("Accuracy score of ",
          clf1.__class__.__name__,
          "=", 100 * accuracy_score(y1_test, Y1_pred))
    print(confusion_matrix(y1_test, Y1_pred))

Accuracy score of  RandomForestClassifier = 99.98815165876778
[[8309    1]
 [   0  130]]
Accuracy score of  KNeighborsClassifier = 99.85781990521328
[[8299   11]
 [   1  129]]
Accuracy score of  SVC = 99.76303317535546
[[8290   20]
 [   0  130]]
Accuracy score of  LogisticRegression = 99.7867298578199
[[8292   18]
 [   0  130]]
Accuracy score of  MLPClassifier = 99.62085308056872
[[8278   32]
 [   0  130]]
Accuracy score of  GaussianNB = 99.50236966824644
[[8268   42]
 [   0  130]]
